ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'RETURN_EXPECTED';
ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'INSPECTION';
ALTER TYPE "InventoryStatus" ADD VALUE IF NOT EXISTS 'QUARANTINED';

ALTER TABLE "Order"
ADD COLUMN "returnRequestedAt" TIMESTAMP(3),
ADD COLUMN "returnReceivedAt" TIMESTAMP(3),
ADD COLUMN "returnInspectedAt" TIMESTAMP(3);
